version: 2.1

executors:
  linux:
    docker:
      - image: cimg/base:2020.01
  macos:
    macos:
      xcode: 11.4

orbs:
  node: circleci/node@4.7.0

jobs:
  build:
    parameters:
      os:
        type: executor
      node-version:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
      - run: npm install
      - run: npm run lint
      - run: npm run report-coverage
      - run: npm run build

workflows:
  matrix-tests:
    jobs:
      - build:
          matrix:
            parameters:
              os: [linux, macos]
              node-version: ["10.24.1", "12.22.7", "14.18.1", "16.13.0"] #sourced from https://www.npmjs.com/package/node?activeTab=versions